version: '3.7'

services:
  builder:
    build:
      context: ./
      target: builder
    image: builder-image
  nginx:
    build:
      context: ./
      target: nginx
    image: nginx
    ports:
      - 3000:80
    depends_on:
      - builder
  cypress:
    build:
      context: ./
      target: test-runner
    image: cypress-test-runner
    working_dir: /app
    depends_on:
      - nginx
    network_mode: host
    environment:
      - CYPRESS_baseUrl=http://localhost:3000
      - BASE_IMAGE=builder-image
      - DISPLAY
    entrypoint: cypress open --project /app